//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Table_Reservation = new HashSet<Table_Reservation>();
        }
    
        public int id_reservation { get; set; }
        public short reservation_number { get; set; }
        public string client_fname { get; set; }
        public string client_lname { get; set; }
        public string client_phone { get; set; }
        public System.TimeSpan time_of_reservation { get; set; }
        public System.DateTime date_of_reservation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Reservation> Table_Reservation { get; set; }
    }
}
