//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Reservation
    {
        public int id_table_reservation { get; set; }
        public int table_id { get; set; }
        public int reservation_id { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual Table Table { get; set; }
    }
}
